apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bdbffquy6-python 
  janus-idp.io/tekton: bdbffquy6-python
  backstage.io/kubernetes-id: bdbffquy6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bdbffquy6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml